/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface CropRecord {
  'id' : string,
  'plantingDate' : string,
  'cropType' : string,
  'irrigationNeeds' : number,
  'zoneId' : string,
  'expectedYield' : number,
}
export interface IrrigationHistory {
  'id' : string,
  'startTime' : Time,
  'status' : boolean,
  'duration' : bigint,
  'waterAmount' : number,
  'zoneId' : string,
}
export interface IrrigationSchedule {
  'id' : string,
  'startTime' : Time,
  'duration' : bigint,
  'waterAmount' : number,
  'zoneId' : string,
}
export interface SensorData {
  'id' : string,
  'soilMoisture' : number,
  'temperature' : number,
  'humidity' : number,
  'timestamp' : Time,
  'phLevel' : number,
  'nitrogenLevel' : number,
  'zoneId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'farmName' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Zone {
  'id' : string,
  'soilType' : string,
  'area' : number,
  'name' : string,
  'coordinates' : Array<Coordinates>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCrop' : ActorMethod<[CropRecord], undefined>,
  'addIrrigationHistory' : ActorMethod<[IrrigationHistory], undefined>,
  'addIrrigationSchedule' : ActorMethod<[IrrigationSchedule], undefined>,
  'addSensorData' : ActorMethod<[SensorData], undefined>,
  'addZone' : ActorMethod<[Zone], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCrop' : ActorMethod<[string], undefined>,
  'deleteIrrigationSchedule' : ActorMethod<[string], undefined>,
  'deleteSensorData' : ActorMethod<[string], undefined>,
  'deleteZone' : ActorMethod<[string], undefined>,
  'getAllCrops' : ActorMethod<[], Array<CropRecord>>,
  'getAllIrrigationSchedules' : ActorMethod<[], Array<IrrigationSchedule>>,
  'getAllZones' : ActorMethod<[], Array<Zone>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrop' : ActorMethod<[string], [] | [CropRecord]>,
  'getIrrigationHistoryByZone' : ActorMethod<
    [string],
    Array<IrrigationHistory>
  >,
  'getIrrigationSchedule' : ActorMethod<[string], [] | [IrrigationSchedule]>,
  'getSensorData' : ActorMethod<[string], [] | [SensorData]>,
  'getSensorDataByZone' : ActorMethod<[string], Array<SensorData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getZone' : ActorMethod<[string], [] | [Zone]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCrop' : ActorMethod<[CropRecord], undefined>,
  'updateIrrigationSchedule' : ActorMethod<[IrrigationSchedule], undefined>,
  'updateZone' : ActorMethod<[Zone], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];