/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CropRecord = IDL.Record({
  'id' : IDL.Text,
  'plantingDate' : IDL.Text,
  'cropType' : IDL.Text,
  'irrigationNeeds' : IDL.Float64,
  'zoneId' : IDL.Text,
  'expectedYield' : IDL.Float64,
});
export const Time = IDL.Int;
export const IrrigationHistory = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : IDL.Bool,
  'duration' : IDL.Nat,
  'waterAmount' : IDL.Float64,
  'zoneId' : IDL.Text,
});
export const IrrigationSchedule = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'duration' : IDL.Nat,
  'waterAmount' : IDL.Float64,
  'zoneId' : IDL.Text,
});
export const SensorData = IDL.Record({
  'id' : IDL.Text,
  'soilMoisture' : IDL.Float64,
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
  'timestamp' : Time,
  'phLevel' : IDL.Float64,
  'nitrogenLevel' : IDL.Float64,
  'zoneId' : IDL.Text,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Zone = IDL.Record({
  'id' : IDL.Text,
  'soilType' : IDL.Text,
  'area' : IDL.Float64,
  'name' : IDL.Text,
  'coordinates' : IDL.Vec(Coordinates),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'farmName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCrop' : IDL.Func([CropRecord], [], []),
  'addIrrigationHistory' : IDL.Func([IrrigationHistory], [], []),
  'addIrrigationSchedule' : IDL.Func([IrrigationSchedule], [], []),
  'addSensorData' : IDL.Func([SensorData], [], []),
  'addZone' : IDL.Func([Zone], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCrop' : IDL.Func([IDL.Text], [], []),
  'deleteIrrigationSchedule' : IDL.Func([IDL.Text], [], []),
  'deleteSensorData' : IDL.Func([IDL.Text], [], []),
  'deleteZone' : IDL.Func([IDL.Text], [], []),
  'getAllCrops' : IDL.Func([], [IDL.Vec(CropRecord)], ['query']),
  'getAllIrrigationSchedules' : IDL.Func(
      [],
      [IDL.Vec(IrrigationSchedule)],
      ['query'],
    ),
  'getAllZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrop' : IDL.Func([IDL.Text], [IDL.Opt(CropRecord)], ['query']),
  'getIrrigationHistoryByZone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IrrigationHistory)],
      ['query'],
    ),
  'getIrrigationSchedule' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IrrigationSchedule)],
      ['query'],
    ),
  'getSensorData' : IDL.Func([IDL.Text], [IDL.Opt(SensorData)], ['query']),
  'getSensorDataByZone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SensorData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getZone' : IDL.Func([IDL.Text], [IDL.Opt(Zone)], ['query']),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCrop' : IDL.Func([CropRecord], [], []),
  'updateIrrigationSchedule' : IDL.Func([IrrigationSchedule], [], []),
  'updateZone' : IDL.Func([Zone], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CropRecord = IDL.Record({
    'id' : IDL.Text,
    'plantingDate' : IDL.Text,
    'cropType' : IDL.Text,
    'irrigationNeeds' : IDL.Float64,
    'zoneId' : IDL.Text,
    'expectedYield' : IDL.Float64,
  });
  const Time = IDL.Int;
  const IrrigationHistory = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : IDL.Bool,
    'duration' : IDL.Nat,
    'waterAmount' : IDL.Float64,
    'zoneId' : IDL.Text,
  });
  const IrrigationSchedule = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'duration' : IDL.Nat,
    'waterAmount' : IDL.Float64,
    'zoneId' : IDL.Text,
  });
  const SensorData = IDL.Record({
    'id' : IDL.Text,
    'soilMoisture' : IDL.Float64,
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
    'timestamp' : Time,
    'phLevel' : IDL.Float64,
    'nitrogenLevel' : IDL.Float64,
    'zoneId' : IDL.Text,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Zone = IDL.Record({
    'id' : IDL.Text,
    'soilType' : IDL.Text,
    'area' : IDL.Float64,
    'name' : IDL.Text,
    'coordinates' : IDL.Vec(Coordinates),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'farmName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCrop' : IDL.Func([CropRecord], [], []),
    'addIrrigationHistory' : IDL.Func([IrrigationHistory], [], []),
    'addIrrigationSchedule' : IDL.Func([IrrigationSchedule], [], []),
    'addSensorData' : IDL.Func([SensorData], [], []),
    'addZone' : IDL.Func([Zone], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCrop' : IDL.Func([IDL.Text], [], []),
    'deleteIrrigationSchedule' : IDL.Func([IDL.Text], [], []),
    'deleteSensorData' : IDL.Func([IDL.Text], [], []),
    'deleteZone' : IDL.Func([IDL.Text], [], []),
    'getAllCrops' : IDL.Func([], [IDL.Vec(CropRecord)], ['query']),
    'getAllIrrigationSchedules' : IDL.Func(
        [],
        [IDL.Vec(IrrigationSchedule)],
        ['query'],
      ),
    'getAllZones' : IDL.Func([], [IDL.Vec(Zone)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrop' : IDL.Func([IDL.Text], [IDL.Opt(CropRecord)], ['query']),
    'getIrrigationHistoryByZone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IrrigationHistory)],
        ['query'],
      ),
    'getIrrigationSchedule' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IrrigationSchedule)],
        ['query'],
      ),
    'getSensorData' : IDL.Func([IDL.Text], [IDL.Opt(SensorData)], ['query']),
    'getSensorDataByZone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SensorData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getZone' : IDL.Func([IDL.Text], [IDL.Opt(Zone)], ['query']),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCrop' : IDL.Func([CropRecord], [], []),
    'updateIrrigationSchedule' : IDL.Func([IrrigationSchedule], [], []),
    'updateZone' : IDL.Func([Zone], [], []),
  });
};

export const init = ({ IDL }) => { return []; };